version: '3.7'
services:
  # frontend:
  #   build: ./frontend/
  #   ports:
  #     - 8003:3000
  #   volumes:
  #     - ./frontend:/application
  backend:
    build: ./backend/
    ports:
      - 8005:5000
    volumes:
      - ./backend/application.py:/application/application.py
